### ISSUE TITLE
How cam I make the Camera View to open faster?

### ISSUE THREAD

**Issue by confile** [tdginternet/TGCameraViewController#27]
The answers here might help you:

http://stackoverflow.com/questions/27203643/how-cam-i-make-the-camera-view-to-open-faster

**Comment by Bruno-Furtado** [comment]
@confile,
The slowness isn't caused by the camera itself.
The effects make it slow.

Some changes [in this code point](https://github.com/tdginternet/TGCameraViewController/blob/2.0.1/TGCameraViewController/Control/TGCameraViewController.m#L90) can improve speed.

You think you could help us in this task?

**Comment by confile** [comment]
I would like to help you but my iOS skills are still at the beginning. I might not be a great help yet.

**Comment by Bruno-Furtado** [comment]
Once we have time we will improve this functionality, ok?
I can close this issue?

**Comment by confile** [comment]
Great I love this App. Thank you for you great support.

**Comment by Bruno-Furtado** [comment]
Thank you for help us so much!
