### ISSUE TITLE
takePhotoTapped not working 

### ISSUE THREAD

**Issue by zoufishanmehdi** [tdginternet/TGCameraViewController#69]
Hi, I'm trying the updated version of TGCamera as camera icon UI was not showing up for iPhone 5 previously. I manually added the updated `Classes` folder under `TGCameraViewController`, but it appears that `func takePhotoTapped:` doesn't work anymore when TGCameraNavigationController is supposed to be presented. Any ideas? Your help would be much appreciated. Thank you!

**Comment by macecchi** [comment]
HI @zoufishanmehdi! Can you tell if takePhotoTapped is being called or if it's just not presenting the view controller?

And how are you importing the library? You're not using CocoaPods?

**Comment by zoufishanmehdi** [comment]
Thank you for your reply. `takePhotoTapped` is being called. It goes to both `let navigationController = TGCameraNavigationController.newWithCameraDelegate(self)`
        `presentViewController(navigationController, animated: true, completion: nil)` but crashes instead of presenting the navigation controller. 

Instead of using cocoapods, I manually dragged `TGCameraSwiftBridgingHeader`, `Resources` and `Classes` i.e Category, Control, Helper, Model, UI. It worked previously but since I updated `Classes` folder today, it doesn't work anymore.

**Comment by macecchi** [comment]
Are there any logs or trace about the crash? Can you try stepping in this method to see what crashes it?

I'd guess this is related to changing how the classes are loaded, which is what I updated today. Could you try using version 2.2.3 to see if it works?

Also, I strongly recommend using CocoaPods, but if that's not an option I'll see what else we can do.

**Comment by zoufishanmehdi** [comment]
Since I set up breakpoints in `TGCameraNavigationController.m` methods, it crashes and goes straight to AppDelegate like the screenshot above instead of calling `func takePhotoTapped`

I will try `pod 'TGCameraViewController', '~> 2.2.3'` and see if that fixes the issue. Thanks again for your help.

**Comment by macecchi** [comment]
No problem. Please tell me if that worked :)

Using CocoaPods should work with the latest version. If it still doesn't work, use `pod 'TGCameraViewController', '2.2.3'` (without `~>`) to use the specific version.

**Comment by zoufishanmehdi** [comment]
Hi, I installed cocoapods as you recommended, but I'm still having issues :/ I set up breakpoints to check whether `takePhotoTapped` is being called and it goes thru all the methods in `TGCameraNavigationController.` It goes thru all the methods and then all I see is a black screen, not a camera with icons. Any ideas? I might have to revert it back to the previous version if this doesn't work.

**Comment by macecchi** [comment]
Can you try with the latest version (2.2.4) and CocoaPods?

On Tue, Jul 26, 2016 at 17:42 Zoufishan Mehdi

<
mailto:Zoufishan Mehdi <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hi, I installed cocoapods as you recommended, but I'm still having issues :/ I set up breakpoints to check whether

takePhotoTapped

is being called and it goes thru all the methods in

TGCameraNavigationController.

It goes thru all the methods and then all I see is a black screen, not a camera with icons. Any ideas? I might have to revert it back to the previous version if this doesn't work.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/tdginternet/TGCameraViewController/issues/69#issuecomment-235398725
, or

**Comment by zoufishanmehdi** [comment]
I tried the latest version (2.2.4) and it works. Thank you so much :)

**Comment by macecchi** [comment]
Yay!
