### ISSUE TITLE
ERROR ITMS-90682: Invalid Bundle - The asset catalog at 'Payload/XXXXX/Assets.car

### ISSUE THREAD

**Issue by ipraba** [tdginternet/TGCameraViewController#75]
First. This is a great component.

When uploading our app to app store we are getting this error from iTC
ERROR ITMS-90682: Invalid Bundle - The asset catalog at 'Payload/XXXXX/Assets.car' can't contain 16-bit or P3 assets if the app supports iOS 9.3 or earlier

This means in our assets we had those non compatible images. After some research i found that the images in TGCameraViewController  are P3 assets. This is causing the app get failed in itunesconnect upload starting from xcode8. I guess the images to be changed to normal image.

Better explained here https://forums.developer.apple.com/thread/60919

**Comment by ipraba** [comment]
Sorry. You already fixed it. Closing it.

**Comment by macecchi** [comment]
Hey @ipraba. Sorry for the inconvenience. As you already noted, this has been fixed in [2.2.6](https://github.com/tdginternet/TGCameraViewController/releases/tag/2.2.6). 

Also note that when building with iOS 10 you have to add some keys to your app's plist: https://github.com/tdginternet/TGCameraViewController#privacy-ios-10.

Thanks!
