### ISSUE TITLE
Photo library button not visible for iPhone 7/iOS 10.2

### ISSUE THREAD

**Issue by zoufishanmehdi** [tdginternet/TGCameraViewController#84]
Hi, I noticed the photo library button (on the bottom right) to use a previously taken picture from the photo library is no longer visible for iPhone 7 and iOS 10.2. This wasn't an issue with iPhone 6S using iOS 10.1. Any ideas?

**Comment by macecchi** [comment]
Hi @zoufishanmehdi! Which version of the Pod are you using?

**Comment by zoufishanmehdi** [comment]
pod 'TGCameraViewController', ‘2.2.4’ I guess I need to update to '2.2.8'

**Comment by macecchi** [comment]
Could you try updating it and see if it worked? I believe there was a fix in #78 which fixed that issue. 😉

**Comment by zoufishanmehdi** [comment]
Yep, I will let you know if that fixes things :)

**Comment by macecchi** [comment]
Hi @zoufishanmehdi. Did you try the latest version? Did it work?

**Comment by zoufishanmehdi** [comment]
Do you recommend updating to '2.2.8' or '2.2.7'? I'm using iPhone 6s but I will be able to test on iPhone 7 tomorrow.

**Comment by macecchi** [comment]
Either one should fix your issue, but upgrade to 2.2.8, the latest :)

On Tue, 10 Jan 2017 at 18:12 Zoufishan Mehdi

<
mailto:Zoufishan Mehdi <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Do you recommend updating to '2.2.8' or '2.2.7'? I'm using iPhone 6s but I will be able to test on iPhone 7 tomorrow.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/tdginternet/TGCameraViewController/issues/84#issuecomment-271684667
, or

**Comment by zoufishanmehdi** [comment]
It works for iPhone 7! Thank you for your help :)
