### ISSUE TITLE
Use custom aspect ration

### ISSUE THREAD

**Issue by Marcopohlo** [tdginternet/TGCameraViewController#89]
Hi, I really like your library, is it possible to use custom aspect ratio? Like 3:4, 16:9 etc? 

Thank you for your answer

**Comment by macecchi** [comment]
Hi @Marcopohlo! There is a feature branch that allows using the default aspect ratio (3:4) in the branch [feature/standard-image-aspect](https://github.com/tdginternet/TGCameraViewController/tree/feature/standard-image-aspect). 

You can check the discussion about this feature in #74.

It only wasn't released yet because I couldn't test it in different devices. If you test it please give me your feedback :)

**Comment by macecchi** [comment]
@Marcopohlo did that work out for you? Can I close the issue and move the discussion to #74?
